# -*- coding: utf-8 -*-
"""Github project - Bike Rental Demand Forecasting .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16r1THvguiDzNSzAg5PQTL1-rTBieBNVq

$$\text{Bike Rental Demand Forecasting}$$
$$\text{Ruocheng Jiang}$$
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df_day = pd.read_csv("day.csv")
df_day.head()

df_day.isnull().sum()

df_day.info()

df_day.describe()

df_prophet = df_day[['dteday', 'cnt']].rename(columns={'dteday': 'ds', 'cnt': 'y'})

#To ensure the dteday is a datetime format:
df_day['dteday'] = pd.to_datetime(df_day['dteday'])

"""### Set the training, testing sets
Training Set: first 718 Rows, dates before '2012-12-17'

Testing Set: last 14 Rows, which is 2 weeks period, dates after '2012-12-17'

 This setup ensures the model is trained and evaluated on separate data, mimicking a real-world scenario.
"""

pip install prophet

from prophet import Prophet

# Prepare dataframe
df_prophet = df_day[['instant', 'dteday', 'cnt', 'season', 'holiday', 'weekday', 'weathersit', 'temp', 'hum', 'windspeed']].rename(
    columns={'dteday': 'ds', 'cnt': 'y'}
)

# Ensure categorical variables are converted appropriately (if needed)
df_prophet['season'] = df_prophet['season'].astype(float)
df_prophet['holiday'] = df_prophet['holiday'].astype(float)
df_prophet['weekday'] = df_prophet['weekday'].astype(float)
df_prophet['weathersit'] = df_prophet['weathersit'].astype(float)

# Define list of regressors
regressors = ['instant', 'season', 'holiday', 'weekday', 'weathersit', 'temp', 'hum', 'windspeed']




# Make sure future also includes it
future = df_prophet[['ds'] + regressors].copy()
future = future[future['ds'] >= '2012-12-17']

# set train set
train = df_prophet[df_prophet['ds'] < '2012-12-17']

# build model
model = Prophet(
    daily_seasonality=True,
    yearly_seasonality=True,
    weekly_seasonality=True
)

# add variables into this regression
for reg in regressors:
    model.add_regressor(reg)

# fit the training data
model.fit(train)

# prediction
future = df_prophet[['ds'] + regressors].copy()
future = future[future['ds'] >= '2012-12-17']
forecast = model.predict(future)

# 14 days (2 week period) prediction
future_forecast = forecast[forecast['ds'] >= '2012-12-17']

# compare actual and predicted forecast
comparison_df = future_forecast[['ds', 'yhat']].merge(
    df_prophet, on='ds', how='left'
)
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(comparison_df['ds'], comparison_df['y'], label='Actual Rentals', marker='o', color='black')
plt.plot(comparison_df['ds'], comparison_df['yhat'], label='Predicted Rentals', marker='x', color='blue')
plt.fill_between(forecast['ds'], forecast['yhat_lower'], forecast['yhat_upper'], alpha=0.2, label='Confidence Interval')

plt.title("Actual vs Prophet Predicted Rentals Model (Next 2 Weeks)")
plt.xlabel("Date")
plt.ylabel("Rental Count")
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
y_true = comparison_df['y']
y_pred = comparison_df['yhat']
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.4f}")

"""While the Prophet model performs reasonably well in capturing the seasonal and weekly sudden changes in the data, the prediction accuracy can still be improved."""

!pip install statsmodels

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import ExponentialSmoothing

print(df_day.columns.tolist())

train = df_day.iloc[:-14]
test = df_day.iloc[-14:]
model = ExponentialSmoothing(
    train['cnt'],
    trend='add',
    seasonal='add',
    seasonal_periods=7
)
fit = model.fit()
forecast = fit.forecast(14)
forecast.index = test.index

plt.figure(figsize=(10,5))
plt.plot(test.index, test['cnt'], label='Actual (Last 14 Days)', marker='o')
plt.plot(forecast.index, forecast, label='Holt-Winters Forecast', linestyle='--', marker='o')
plt.title("Actual vs Holt-Winters Forecast Rentals Model (Next 2 Weeks)")
plt.ylabel("Rental Count")
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

y_true = test['cnt']
y_pred = forecast


mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"R² Score: {r2:.4f}")